version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=je mappelle riccardo et je suis informaticien jadore les voitures et les pates
    restart: always

  backup:
    build: ./backup
    volumes:
      - ./data:/data:ro
      - ./backups:/backups
    restart: always
